### ISSUE TITLE
Registro de Alumnos

### ISSUE THREAD

**Issue by esc-granadilla** [esc-granadilla/campus#4]
Frontend y Backend
Se programara un modulo que permitirá ingresar y registrar a los Alumnos.

**Comment by dabakura** [comment]
Se empezo a trabajar en el registro de alumnos

**Comment by esc-granadilla** [comment]
Se produjo un error Cross-Origin Resource Sharing (CORS) el cuál hace que no sea viable la elaboración de la APi de Laravel.

Esto debido a que no se puede instalar el paquete barryvdh dado que esto necesita una versión igual o mayor al 5.5 y el proyecto fue construido con la versión 5.4 de Laravel por que está versión es la única que no necesita de la última versión de php y el servidor donde se montara solo nos dispone de la versión 7.0 de php.

Más información
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors
https://github.com/barryvdh/laravel-cors

**Comment by dabakura** [comment]
Se creo y termino la tarea
